name: APK Derleyici
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v4

      - name: APK Derle (Kivy Resmi Docker Sistemi)
        uses: docker://kivy/buildozer:latest
        with:
          entrypoint: /bin/bash
          args: -c "yes | buildozer android debug"

      - name: APK Dosyasını Çıkart
        uses: actions/upload-artifact@v4
        with:
          name: iptracker-apk
          path: bin/*.apk
